INSERT INTO
  "public"."PartnerCategories" ("Name", "Description", "Discriminator", "Status", "CreatedBy", "CreatedDate", "LastModifiedBy", "IsDeleted", "DeletedBy")
VALUES
  ('Academic, Training and Research','Academic, Training and Research', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Foundation','Foundation', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Government: Non-OECD/DAC','Government: Non-OECD/DAC', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Government: OECD/DAC','Government: OECD/DAC', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('IFI International Financial Institutions','IFI International Financial Institutions', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Multi-partner initiatives & Vertical Funds','Multi-partner initiatives & Vertical Funds', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Non-governmental Organizations','Non-governmental Organizations', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Other','Other', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Private Sector','Private Sector', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Public Private Partnership','Public Private Partnership', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Regional and other Intergovernmental Organizations','Regional and other Intergovernmental Organizations', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('United Nations','United Nations', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Brazil','Brazil', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Liechtenstein','Liechtenstein', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Moroco','Moroco', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Panama','Panama', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Paraguay','Paraguay', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Peru','Peru', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Saudi Arabia','Saudi Arabia', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('South Africa','South Africa', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Türkiye','Türkiye', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Austria','Austria', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Canada','Canada', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Denmark','Denmark', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Germany','Germany', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Iceland','Iceland', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Luxembourg','Luxembourg', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Netherlands','Netherlands', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Norway','Norway', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Portugal','Portugal', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('South Korea','South Korea', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Spain','Spain', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Sweden','Sweden', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Switzerland','Switzerland', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UK United Kingdom','UK United Kingdom', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('USA United States of America','USA United States of America', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('WBG World Bank Group','WBG World Bank Group', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('3MDG/Myanmar Access for Health','3MDG/Myanmar Access for Health', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('EIF Enhanced Integrated Framework','EIF Enhanced Integrated Framework', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('AU African Union','AU African Union', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('EU European Union','EU European Union', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UN EOSG Executive Office of the Secretary-General','UN EOSG Executive Office of the Secretary-General', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNDP United Nations Development Programme','UNDP United Nations Development Programme', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNOPS United Nations Office for Project Services','UNOPS United Nations Office for Project Services', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('WHO / PAHO World Health Organization incl. PAHO','WHO / PAHO World Health Organization incl. PAHO', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('QA NEW PARTNER CATEGORY - WITHOUT PARENT','SAMPLE DESC FOR PARTNER CATEGORY', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('QA NEW PARTNER CATEGORY - WITH PARENT','SAMPLE DESC', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Lesotho','Lesotho', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Parent 1','Parent 1', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Child1','child1', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Grand Parent1','Grand Parent1', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('CODEMGE Minas Gerais Development Company','CODEMGE Minas Gerais Development Company', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Other Donors','Other Donors', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Other Sponsors','Other Sponsors', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('NIC-Union Europea','NIC-Union Europea', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('BCBRP Meritorious Fire Department of the Republic of Panama','BCBRP Meritorious Fire Department of the Republic of Panama', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('INCAP Institute of Nutrition of Central America and Panama','INCAP Institute of Nutrition of Central America and Panama', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('IPM Instituto de Previsión Militar','IPM Instituto de Previsión Militar', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Instituto Nacional de Previsión del Magisterio INPREMA','Instituto Nacional de Previsión del Magisterio INPREMA', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Nippon Foundation','Nippon Foundation', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('AKF Aga Khan Foundation','AKF Aga Khan Foundation', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('IDOR Instituto D''or De Pesquisa E Ensino','IDOR Instituto D''or De Pesquisa E Ensino', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Mohammed bin Rashid Al Maktoum Foundation','Mohammed bin Rashid Al Maktoum Foundation', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Omidyar Network','Omidyar Network', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Doen Foundation','Doen Foundation', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Wellspring Foundation','Wellspring Foundation', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('REALL Real Equity for All','REALL Real Equity for All', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Jordan River Foundation','Jordan River Foundation', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Rockefeller Philanthropy Advisors','Rockefeller Philanthropy Advisors', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('PeaceNexus Foundation','PeaceNexus Foundation', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Yajilarra Trust','Yajilarra Trust', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Bill and Melinda Gates Foundation','Bill and Melinda Gates Foundation', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('CRDF Global Civilian Research and Development Foundation','CRDF Global Civilian Research and Development Foundation', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Clinton Foundation','Clinton Foundation', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Stichting Radio La Benevolencija Humanitarian Tools Foundation','Stichting Radio La Benevolencija Humanitarian Tools Foundation', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('IKEA Foundation','IKEA Foundation', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Sequoia Climate Fund','Sequoia Climate Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('KAS Konrad-Adenauer-Stiftung','KAS Konrad-Adenauer-Stiftung', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('EGPAF Elizabeth Glaser Pediatric AIDS Foundation','EGPAF Elizabeth Glaser Pediatric AIDS Foundation', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Paul G. Allen Family Foundation','Paul G. Allen Family Foundation', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Ford Foundation','Ford Foundation', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Petunia Foundation','Petunia Foundation', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Purpose Foundation','Purpose Foundation', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Eli Lilly and Company Foundation','Eli Lilly and Company Foundation', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('GAP Foundation','GAP Foundation', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Temasek Foundation','Temasek Foundation', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Kochon Foundation','Kochon Foundation', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Open Society Afghanistan','Open Society Afghanistan', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('United Nations Foundation','United Nations Foundation', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('MacArthur Foundation','MacArthur Foundation', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('WAPCAS Ghana-West Africa Program to Combat AIDS and STI','WAPCAS Ghana-West Africa Program to Combat AIDS and STI', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('FIND Foundation for Innovative New Diagnostics','FIND Foundation for Innovative New Diagnostics', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Chinese Red Cross Foundation','Chinese Red Cross Foundation', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('GAIN Global Alliance for Improved Nutrition','GAIN Global Alliance for Improved Nutrition', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('ECEAP Estonian Center for Eastern Partnership','ECEAP Estonian Center for Eastern Partnership', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('CIFF Children''s Investment Fund Foundation','CIFF Children''s Investment Fund Foundation', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Quadrature Climate Foundation','Quadrature Climate Foundation', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Yemen Famine Relief Fund','Yemen Famine Relief Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Walmart Foundation','Walmart Foundation', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Rockefeller Foundation','Rockefeller Foundation', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('MAVA Foundation','MAVA Foundation', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('R20 Regions of Climate Action','R20 Regions of Climate Action', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Italy','Italy', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Albania','Albania', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Algeria','Algeria', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Andorra','Andorra', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Angola','Angola', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Antigua and Barbuda','Antigua and Barbuda', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Argentina','Argentina', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Armenia','Armenia', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Azerbaijan','Azerbaijan', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Bahamas','Bahamas', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Bahrain','Bahrain', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Bangladesh','Bangladesh', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Barbados','Barbados', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Belarus','Belarus', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Belize','Belize', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Benin','Benin', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Bhutan','Bhutan', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Bolivia (Plurinational State of)','Bolivia (Plurinational State of)', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Bosnia and Herzegovina','Bosnia and Herzegovina', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Botswana','Botswana', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Brunei Darussalam','Brunei Darussalam', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Bulgaria','Bulgaria', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Burkina Faso','Burkina Faso', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Burundi','Burundi', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Democratic People''s Republic of Korea','Democratic People''s Republic of Korea', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Cameroon','Cameroon', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Cape Verde','Cape Verde', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Central African Republic','Central African Republic', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Chad','Chad', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Chile','Chile', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Colombia','Colombia', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Comoros','Comoros', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Cook Islands','Cook Islands', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Democratic Republic of the Congo','Democratic Republic of the Congo', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Croatia','Croatia', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Cuba','Cuba', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Cyprus','Cyprus', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Czechia','Czechia', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Ghana','Ghana', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Jordan','Jordan', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Kazakhstan','Kazakhstan', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Grenada','Grenada', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Kenya','Kenya', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Kiribati','Kiribati', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Kuwait','Kuwait', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Kyrgyzstan','Kyrgyzstan', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Lao People''s Democratic Republic','Lao People''s Democratic Republic', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Latvia','Latvia', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Lebanon','Lebanon', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Liberia','Liberia', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Oman','Oman', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Pakistan','Pakistan', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Palau','Palau', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Papua New Guinea','Papua New Guinea', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Philippines','Philippines', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Afghanistan','Afghanistan', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Cambodia','Cambodia', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Côte d''Ivoire','Côte d''Ivoire', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Congo','Congo', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Djibouti','Djibouti', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Dominica','Dominica', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Dominican Republic','Dominican Republic', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Ecuador','Ecuador', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Egypt','Egypt', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('El Salvador','El Salvador', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Equatorial Guinea','Equatorial Guinea', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Eritrea','Eritrea', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Estonia','Estonia', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Fiji','Fiji', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Haiti','Haiti', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Iraq','Iraq', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Gabon','Gabon', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Gambia','Gambia', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Georgia','Georgia', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Guatemala','Guatemala', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Guinea','Guinea', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Guyana','Guyana', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Indonesia','Indonesia', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Jamaica','Jamaica', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Lithuania','Lithuania', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Iran (Islamic Republic of)','Iran (Islamic Republic of)', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Holy See','Holy See', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Hungary','Hungary', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Kosovo (under UNSCR 1244/99)','Kosovo (under UNSCR 1244/99)', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Madagascar','Madagascar', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Malawi','Malawi', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Malaysia','Malaysia', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Maldives','Maldives', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Mali','Mali', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Malta','Malta', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Marshall Islands','Marshall Islands', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Mauritania','Mauritania', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Mauritius','Mauritius', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Mexico','Mexico', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Micronesia (Federated States of)','Micronesia (Federated States of)', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('South Sudan','South Sudan', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Monaco','Monaco', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Montenegro','Montenegro', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Mozambique','Mozambique', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Namibia','Namibia', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Nauru','Nauru', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Niger','Niger', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Nepal','Nepal', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Mongolia','Mongolia', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Myanmar','Myanmar', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Nicaragua','Nicaragua', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Nigeria','Nigeria', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Republic of Moldova','Republic of Moldova', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Romania','Romania', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Russian Federation','Russian Federation', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Rwanda','Rwanda', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Saint Kitts and Nevis','Saint Kitts and Nevis', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Saint Lucia','Saint Lucia', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Saint Vincent and the Grenadines','Saint Vincent and the Grenadines', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Samoa','Samoa', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('San Marino','San Marino', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Sao Tome and Principe','Sao Tome and Principe', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Senegal','Senegal', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Suriname','Suriname', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Serbia','Serbia', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Seychelles','Seychelles', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Sierra Leone','Sierra Leone', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Singapore','Singapore', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Slovakia','Slovakia', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Solomon Islands','Solomon Islands', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Somalia','Somalia', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Sri Lanka','Sri Lanka', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Sudan','Sudan', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('State of Palestine','State of Palestine', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Syrian Arab Republic','Syrian Arab Republic', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Tajikistan','Tajikistan', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Thailand','Thailand', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('North Macedonia','North Macedonia', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Timor-Leste','Timor-Leste', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Togo','Togo', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Tonga','Tonga', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Trinidad and Tobago','Trinidad and Tobago', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Tunisia','Tunisia', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('United Republic of Tanzania','United Republic of Tanzania', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Guinea-Bissau','Guinea-Bissau', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Turkmenistan','Turkmenistan', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Tuvalu','Tuvalu', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Uganda','Uganda', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('United Arab Emirates','United Arab Emirates', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Uruguay','Uruguay', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Uzbekistan','Uzbekistan', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Vanuatu','Vanuatu', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Venezuela (Bolivarian Republic of)','Venezuela (Bolivarian Republic of)', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Viet Nam','Viet Nam', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Yemen','Yemen', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Zambia','Zambia', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Zimbabwe','Zimbabwe', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Yugoslavia','Yugoslavia', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Virgin Islands of the United States','Virgin Islands of the United States', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Czechoslovakia','Czechoslovakia', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Antilles','Antilles', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('China, Hong Kong Special Administrative Region','China, Hong Kong Special Administrative Region', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('New Hebrides Condominium','New Hebrides Condominium', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Niue','Niue', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Pacific Multi Islands','Pacific Multi Islands', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('New Zealand territory of Tokelau','New Zealand territory of Tokelau', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Trust Territory of the Pacific Islands','Trust Territory of the Pacific Islands', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Curaçao','Curaçao', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Sint Maarten (Dutch part)','Sint Maarten (Dutch part)', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('QFFD Qatar Fund for Development','QFFD Qatar Fund for Development', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('China','China', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('India','India', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Japan','Japan', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Libya','Libya', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Qatar','Qatar', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('France','France', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Greece','Greece', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Israel','Israel', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Poland','Poland', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Belgium','Belgium', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Finland','Finland', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Ireland','Ireland', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Ukraine','Ukraine', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Eswatini','Eswatini', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Ethiopia','Ethiopia', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Honduras','Honduras', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Australia','Australia', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Costa Rica','Costa Rica', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('New Zealand','New Zealand', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Tasmim Libya Consulting and Engineering','Tasmim Libya Consulting and Engineering', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('FunziLife OY','FunziLife OY', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Takeda Pharmaceutical Company Limited','Takeda Pharmaceutical Company Limited', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Macfadden','Macfadden', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Roche Diagnostics International AG','Roche Diagnostics International AG', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Mitsubishi','Mitsubishi', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Microsoft Corporation','Microsoft Corporation', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('OTB The Office of Tony Blair','OTB The Office of Tony Blair', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Labomersa','Labomersa', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Crown Agents','Crown Agents', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Accenture','Accenture', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Stanbic Bank Ghana','Stanbic Bank Ghana', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Novo Nordisk AS','Novo Nordisk AS', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('ABDIB Associação Brasileira da Infraestrutura e Indústrias de Base','ABDIB Associação Brasileira da Infraestrutura e Indústrias de Base', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('BEGECA Beschaffungsgesellschaft mbH','BEGECA Beschaffungsgesellschaft mbH', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('RAP Regimen de Aportaciones Privadas','RAP Regimen de Aportaciones Privadas', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Red Sea Trading Corporation Ltd.','Red Sea Trading Corporation Ltd.', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Mott MacDonald','Mott MacDonald', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Estee Lauder Companies','Estee Lauder Companies', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('BCG Boston Consulting Group','BCG Boston Consulting Group', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Abt Associates','Abt Associates', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('SkyOcean Group Holdings','SkyOcean Group Holdings', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Miyamoto International','Miyamoto International', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Coca Cola Company','Coca Cola Company', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('DNA Genotek','DNA Genotek', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Sony Group Corporation','Sony Group Corporation', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Hemas PLC','Hemas PLC', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Checci and Company Consulting','Checci and Company Consulting', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Marine Information Service B.V.','Marine Information Service B.V.', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('CISCO System','CISCO System', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('FTB Foreign Trade Bank of Cambodia','FTB Foreign Trade Bank of Cambodia', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Philips','Philips', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('WEM Worldwide Export Management','WEM Worldwide Export Management', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('South Sudan Common Humanitarian Fund','South Sudan Common Humanitarian Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Ebola Response MPTF','Ebola Response MPTF', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Syria Emergency Response Fund','Syria Emergency Response Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UN Multi-Partner Trust Fund for Somalia (Somalia UN MPTF)','UN Multi-Partner Trust Fund for Somalia (Somalia UN MPTF)', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNDF United Nations Fund for Recovery Reconstruction and Development in Darfur','UNDF United Nations Fund for Recovery Reconstruction and Development in Darfur', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UN General Trust Fund','UN General Trust Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('CERF Central Emergency Response Fund','CERF Central Emergency Response Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNPBF United Nations Peacebuilding Fund','UNPBF United Nations Peacebuilding Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNVFTC United Nations Voluntary Fund for Technical Co-operation in the Field of','UNVFTC United Nations Voluntary Fund for Technical Co-operation in the Field of', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNVFVT United Nations Voluntary Fund for Victims of Torture','UNVFVT United Nations Voluntary Fund for Victims of Torture', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNVFD United Nations Voluntary Fund on Disability','UNVFD United Nations Voluntary Fund on Disability', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNDEF United Nations Democracy Fund','UNDEF United Nations Democracy Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNFIP United Nations Fund for International Partnerships','UNFIP United Nations Fund for International Partnerships', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UN-Water Inter-agency Trust Fund','UN-Water Inter-agency Trust Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Albania One UN Coherence Fund','Albania One UN Coherence Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Bhutan UN Country Fund','Bhutan UN Country Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Botswana UN Country Fund','Botswana UN Country Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Cape Verde Transition Fund','Cape Verde Transition Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Central African Republic Common Humanitarian Fund','Central African Republic Common Humanitarian Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('CFIA United Nations Central Fund for Influenza Action','CFIA United Nations Central Fund for Influenza Action', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Community-based Based Adaptation to Climate Change','Community-based Based Adaptation to Climate Change', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Comoros One UN Fund','Comoros One UN Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('DCPSF Darfur Community Peace and Stability Fund','DCPSF Darfur Community Peace and Stability Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('DRC Pooled Fund','DRC Pooled Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('DRC Stabilization and Recovery','DRC Stabilization and Recovery', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Ethiopia One UN Fund','Ethiopia One UN Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Human Rights Mainstreaming Trust Fund','Human Rights Mainstreaming Trust Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Indonesia Disaster Recovery Trust Fund','Indonesia Disaster Recovery Trust Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Iraq UNDAF Trust Fund','Iraq UNDAF Trust Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('JP Armed Violence Prevention','JP Armed Violence Prevention', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('JP LGSP-LIC Bangladesh Local Governance Support Project – Learning and Innovatio','JP LGSP-LIC Bangladesh Local Governance Support Project – Learning and Innovatio', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('JP Chad DIS Security','JP Chad DIS Security', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('JP DRC Microfinance II','JP DRC Microfinance II', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('JP DRC Security Sect Reform','JP DRC Security Sect Reform', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('JP Guatemala Maya Programme','JP Guatemala Maya Programme', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('JP Guatemala Rural Dev','JP Guatemala Rural Dev', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('JP Kazakhstan Innov Aprch RPSS','JP Kazakhstan Innov Aprch RPSS', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('JP Kenya HIV and AIDS','JP Kenya HIV and AIDS', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('JP Kosovo Domestic Violence','JP Kosovo Domestic Violence', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('JP Lao Governance and Public Administration Reform','JP Lao Governance and Public Administration Reform', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('JP Liberia Food Security','JP Liberia Food Security', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('JP Liberia Gender Equality','JP Liberia Gender Equality', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('JP Mali Agro Pastoral Products','JP Mali Agro Pastoral Products', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('JP Moldova Integrated Local Development Programme','JP Moldova Integrated Local Development Programme', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('JP Nepal LGCDP Local Governance and Community Development Programme','JP Nepal LGCDP Local Governance and Community Development Programme', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('JP Serbia SCILD Strengthening Capacity for Inclusive Local Development','JP Serbia SCILD Strengthening Capacity for Inclusive Local Development', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('JP Solomon Islands PGSP Provincial Governance Strengthening Programme','JP Solomon Islands PGSP Provincial Governance Strengthening Programme', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('JP Somalia Local Governance and Decentralized Service Delivery','JP Somalia Local Governance and Decentralized Service Delivery', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('JP TFYR SNC PDV Macedonia Strengthening National Capacities to Prevent Domestic','JP TFYR SNC PDV Macedonia Strengthening National Capacities to Prevent Domestic', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('JP Timor-Leste INFUSE Inclusive Finance for Under-Served Economy','JP Timor-Leste INFUSE Inclusive Finance for Under-Served Economy', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('JP Timor-Leste LGSP Local Governance Support Programme','JP Timor-Leste LGSP Local Governance Support Programme', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('JP Uganda Gender Equality','JP Uganda Gender Equality', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('JP Uganda Support for AIDS','JP Uganda Support for AIDS', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Kiribati One UN Fund','Kiribati One UN Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Kyrgyzstan One Fund','Kyrgyzstan One Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Lebanon Recovery Fund','Lebanon Recovery Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Lesotho One UN Fund','Lesotho One UN Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Malawi One UN Fund','Malawi One UN Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Maldives One UN Fund','Maldives One UN Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('MDG Achievement Fund','MDG Achievement Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Montenegro UN Country Fund','Montenegro UN Country Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Mozambique One UN Fund','Mozambique One UN Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Nepal - UN Peace Fund','Nepal - UN Peace Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Pakistan One Fund','Pakistan One Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('PBF Peacebuilding Fund','PBF Peacebuilding Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('PNG UN Country Fund','PNG UN Country Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('REDD+ JP Partnership Support','REDD+ JP Partnership Support', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Rwanda One UN Fund','Rwanda One UN Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Sierra Leone MDTF','Sierra Leone MDTF', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Somalia Common Humanitarian Fund','Somalia Common Humanitarian Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('SSRF South Sudan Recovery Fund','SSRF South Sudan Recovery Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Sudan Common Humanitarian Fund','Sudan Common Humanitarian Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Tanzania One UN Fund','Tanzania One UN Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UN Action Against Sexual Violence in Conflict','UN Action Against Sexual Violence in Conflict', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UN Civil Society Trust Fund','UN Civil Society Trust Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNIPP United Nations Indigenous Peoples’ Partnership','UNIPP United Nations Indigenous Peoples’ Partnership', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UN Trust Fund for Human Security','UN Trust Fund for Human Security', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UN Trust Fund to End Volence Against Women','UN Trust Fund to End Volence Against Women', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Haiti Reconstruction Fund','Haiti Reconstruction Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNDG Iraq Trust Fund','UNDG Iraq Trust Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UN-REDD Programme Fund','UN-REDD Programme Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Uruguay One UN Coherence Fund','Uruguay One UN Coherence Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Viet Nam One Plan Fund I','Viet Nam One Plan Fund I', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Viet Nam One Plan Fund II','Viet Nam One Plan Fund II', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Other UNDP MDTF','Other UNDP MDTF', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Other UNDP JP','Other UNDP JP', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UN Fund for Sudano-Sahelian Activities','UN Fund for Sudano-Sahelian Activities', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('VTF UN Voluntary Trust Fund for Assistance in Mine Action','VTF UN Voluntary Trust Fund for Assistance in Mine Action', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UN Haiti Cholera Response Multi-Partner Trust Fund','UN Haiti Cholera Response Multi-Partner Trust Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNTFHS United Nations Trust Fund for Human Security','UNTFHS United Nations Trust Fund for Human Security', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNITLIFE United Nations Initiative Fighting Chronic Malnutrition Through Innovat','UNITLIFE United Nations Initiative Fighting Chronic Malnutrition Through Innovat', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('United Nations Multi-Partner Trust Fund Office','United Nations Multi-Partner Trust Fund Office', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('United Nations Sri Lanka SDG Multi-Partner Trust Fund','United Nations Sri Lanka SDG Multi-Partner Trust Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNSDG United Nations Sustainable Development Group (formerly UNDG)','UNSDG United Nations Sustainable Development Group (formerly UNDG)', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('CEB United Nations System Chief Executives Board for Coordination','CEB United Nations System Chief Executives Board for Coordination', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('United Nations Resident Coordinator Office - Sri Lanka','United Nations Resident Coordinator Office - Sri Lanka', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('IAEA International Atomic Energy Agency','IAEA International Atomic Energy Agency', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('OPCW Organisation for the Prohibition of Chemical Weapons','OPCW Organisation for the Prohibition of Chemical Weapons', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('IOM International Organization for Migration','IOM International Organization for Migration', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('WTO World Trade Organization','WTO World Trade Organization', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNAIDS Joint United Nations Programme on HIV/AIDS','UNAIDS Joint United Nations Programme on HIV/AIDS', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNV United Nations Volunteers','UNV United Nations Volunteers', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('WFP United Nations World Food Programme','WFP United Nations World Food Programme', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNICEF United Nations Children''s Fund','UNICEF United Nations Children''s Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UN-HABITAT United Nations Human Settlement Programme','UN-HABITAT United Nations Human Settlement Programme', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNFPA United Nations Population Fund','UNFPA United Nations Population Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UN Technology Bank for LDC','UN Technology Bank for LDC', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNCDF United Nations Capital Development Fund','UNCDF United Nations Capital Development Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNEP United Nations Environment Programme','UNEP United Nations Environment Programme', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('ICC International Computing Centre','ICC International Computing Centre', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNGM United Nations Global Marketplace','UNGM United Nations Global Marketplace', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNHCR Office of the United Nations High Commissioner for Refugees','UNHCR Office of the United Nations High Commissioner for Refugees', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNRWA United Nations Relief and Works Agency for Palestine Refugees in the Near','UNRWA United Nations Relief and Works Agency for Palestine Refugees in the Near', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNCTAD United Nations Conference on Trade and Development','UNCTAD United Nations Conference on Trade and Development', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UN WOMEN United Nations Entity for Gender Equality and the Empowerment of Women','UN WOMEN United Nations Entity for Gender Equality and the Empowerment of Women', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('ITC International Trade Centre','ITC International Trade Centre', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNIFEM United Nations Development Fund for Women','UNIFEM United Nations Development Fund for Women', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UN ECLAC Economic Commission for Latin America and the Caribbean','UN ECLAC Economic Commission for Latin America and the Caribbean', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UN ECE Economic Commission for Europe','UN ECE Economic Commission for Europe', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UN ESCWA Economic and Social Commission for Western Asia','UN ESCWA Economic and Social Commission for Western Asia', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UN ECA Economic Commission for Africa','UN ECA Economic Commission for Africa', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UN ESCAP Economic and Social Commission for Asia and the Pacific','UN ESCAP Economic and Social Commission for Asia and the Pacific', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNOIP United Nations Office of the Iraq Programme','UNOIP United Nations Office of the Iraq Programme', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNSCN United Nations System Standing Committee on Nutrition','UNSCN United Nations System Standing Committee on Nutrition', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('MINUJUSTH United Nations Mission for Justice Support in Haiti','MINUJUSTH United Nations Mission for Justice Support in Haiti', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNMIK United Nations Interim Administration Mission in Kosovo','UNMIK United Nations Interim Administration Mission in Kosovo', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNISFA United Nations Interim Security Force in Abyei','UNISFA United Nations Interim Security Force in Abyei', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNAKRT United Nations Assistance to the Khmer Rouge Trials','UNAKRT United Nations Assistance to the Khmer Rouge Trials', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNSOS United Nations Support Office in Somalia','UNSOS United Nations Support Office in Somalia', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('MINUSCA United Nations Multidimensional Integrated Stabilization Mission in the','MINUSCA United Nations Multidimensional Integrated Stabilization Mission in the', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('MINURSO United Nations Mission for the Referendum in Western Sahara','MINURSO United Nations Mission for the Referendum in Western Sahara', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNIPSIL United Nations Integrated Peacebuilding Office in Sierra Leone','UNIPSIL United Nations Integrated Peacebuilding Office in Sierra Leone', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNROD United Nations Register of Damage','UNROD United Nations Register of Damage', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNSCEAR United Nations Scientific Committee on the Effects of Atomic Radiation','UNSCEAR United Nations Scientific Committee on the Effects of Atomic Radiation', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNAMI United Nations Assistance Mission for Iraq','UNAMI United Nations Assistance Mission for Iraq', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNMIL United Nations Mission in Liberia','UNMIL United Nations Mission in Liberia', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('MONUSCO United Nations Organization Stabilization Mission in the Democratic Repu','MONUSCO United Nations Organization Stabilization Mission in the Democratic Repu', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('MENUB United Nations Electoral Observation Mission in Burundi','MENUB United Nations Electoral Observation Mission in Burundi', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNOCT United Nations Office of Counter-Terrorism','UNOCT United Nations Office of Counter-Terrorism', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNTSO United Nations Truce Supervision','UNTSO United Nations Truce Supervision', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNORCID United Nations Office for REDD+ Coordination in Indonesia','UNORCID United Nations Office for REDD+ Coordination in Indonesia', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNIFIL United Nations Interim Force in Lebanon','UNIFIL United Nations Interim Force in Lebanon', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNIOGBIS United Nations Integrated Peacebuilding Office in Guinea-Bissau','UNIOGBIS United Nations Integrated Peacebuilding Office in Guinea-Bissau', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNMISS United Nations Mission in the Republic of South Sudan','UNMISS United Nations Mission in the Republic of South Sudan', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNAMA United Nations Assistance Mission in Afghanistan','UNAMA United Nations Assistance Mission in Afghanistan', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('MINUSMA United Nations Multidimensional Integrated Stabilization Mission in Mali','MINUSMA United Nations Multidimensional Integrated Stabilization Mission in Mali', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('BINUCA United Nations Integrated Peacebuilding Office in the Central African Rep','BINUCA United Nations Integrated Peacebuilding Office in the Central African Rep', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNSOM United Nations Assistance Mission in Somalia','UNSOM United Nations Assistance Mission in Somalia', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNSMIL United Nations Support Mission in Libya','UNSMIL United Nations Support Mission in Libya', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNMOGIP United Nations Military Observer Group in India and Pakistan','UNMOGIP United Nations Military Observer Group in India and Pakistan', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNOCI United Nations Operation in Côte d''Ivoire','UNOCI United Nations Operation in Côte d''Ivoire', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('MINUSTAH United Nations Stabilization Mission in Haiti','MINUSTAH United Nations Stabilization Mission in Haiti', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNOCI United Nations Operation in Cote d''Ivoire','UNOCI United Nations Operation in Cote d''Ivoire', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNMIT United Nations Integrated Mission in Timor-Leste','UNMIT United Nations Integrated Mission in Timor-Leste', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNFICYP United Nations Peacekeeping Force in Cyprus','UNFICYP United Nations Peacekeeping Force in Cyprus', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNMIS United Nations Mission in Sudan','UNMIS United Nations Mission in Sudan', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UN United Nations','UN United Nations', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UN OHCHR Office of the United Nations High Commissioner for Human Rights','UN OHCHR Office of the United Nations High Commissioner for Human Rights', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UN DPO Department of Peace Operations','UN DPO Department of Peace Operations', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('OIOS Office of Internal Oversight Services','OIOS Office of Internal Oversight Services', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UN DCO United Nations Development Coordination Office','UN DCO United Nations Development Coordination Office', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UN DPPA Department of Political and Peacebuilding Affairs','UN DPPA Department of Political and Peacebuilding Affairs', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UN DMSPC Department of Management Strategy, Policy and Compliance','UN DMSPC Department of Management Strategy, Policy and Compliance', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNODC United Nations Office on Drugs and Crime','UNODC United Nations Office on Drugs and Crime', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('OSAA Office of the Special Adviser on Africa','OSAA Office of the Special Adviser on Africa', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNON United Nations Office at Nairobi','UNON United Nations Office at Nairobi', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UN DESA Department of Economic and Social Affairs','UN DESA Department of Economic and Social Affairs', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UN DOS Department of Operational Support','UN DOS Department of Operational Support', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNOWA United Nations Office for West Africa','UNOWA United Nations Office for West Africa', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UN OLA Office of Legal Affairs','UN OLA Office of Legal Affairs', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UN OCHA Office for the Coordination of Humanitarian Affairs','UN OCHA Office for the Coordination of Humanitarian Affairs', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UN-OHRLLS Office of the High Representative for the Least Developed Countries, L','UN-OHRLLS Office of the High Representative for the Least Developed Countries, L', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UN DGC Department of Global Communications','UN DGC Department of Global Communications', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNOV United Nations Office at Vienna','UNOV United Nations Office at Vienna', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNDRR United Nations Office for Disaster Risk Reduction','UNDRR United Nations Office for Disaster Risk Reduction', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNODA Office for Disarmament Affairs','UNODA Office for Disarmament Affairs', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNDSS Department of Safety and Security','UNDSS Department of Safety and Security', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UN DGACM Department for General Assembly and Conference Management','UN DGACM Department for General Assembly and Conference Management', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNOCA United Nations Regional Office for Central Africa','UNOCA United Nations Regional Office for Central Africa', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNOG United Nations Office at Geneva','UNOG United Nations Office at Geneva', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('SRSG CAAC Office of the Special Representative of the Secretary-General for Chil','SRSG CAAC Office of the Special Representative of the Secretary-General for Chil', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNOAU United Nations Office to the African Union','UNOAU United Nations Office to the African Union', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNRISD United Nations Research Institute for Social Development','UNRISD United Nations Research Institute for Social Development', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNIDIR United Nations Institute for Disarmament Research','UNIDIR United Nations Institute for Disarmament Research', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNSSC United Nations System Staff College','UNSSC United Nations System Staff College', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNITAR United Nations Institute for Training and Research','UNITAR United Nations Institute for Training and Research', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNU United Nations University','UNU United Nations University', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNICRI United Nations Interregional Crime and Justice Research Institute','UNICRI United Nations Interregional Crime and Justice Research Institute', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNCCD United Nations Convention to Combat Desertification','UNCCD United Nations Convention to Combat Desertification', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNFCCC United Nations Framework Convention on Climate Change','UNFCCC United Nations Framework Convention on Climate Change', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('CRPD Convention on the Rights of Persons with Disabilities','CRPD Convention on the Rights of Persons with Disabilities', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNIDO United Nations Industrial Development Organization','UNIDO United Nations Industrial Development Organization', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNESCO United Nations Educational, Scientific and Cultural Organization','UNESCO United Nations Educational, Scientific and Cultural Organization', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UPU Universal Postal Union','UPU Universal Postal Union', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('ICAO International Civil Aviation Organization','ICAO International Civil Aviation Organization', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('WIPO World Intellectual Property Organization','WIPO World Intellectual Property Organization', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('IFAD International Fund for Agricultural Development','IFAD International Fund for Agricultural Development', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('FAO Food and Agriculture Organization of the United Nations','FAO Food and Agriculture Organization of the United Nations', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('IMO International Maritime Organization','IMO International Maritime Organization', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNWTO World Tourism Organization','UNWTO World Tourism Organization', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('ILO International Labour Organization','ILO International Labour Organization', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('ITU International Telecommunication Union','ITU International Telecommunication Union', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('WMO World Meteorological Organization','WMO World Meteorological Organization', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('CPI Community Partners International','CPI Community Partners International', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('INS-NGO (International)','INS-NGO (International)', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Assist International','Assist International', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('CORDAID Catholic Organisation for Relief and Development Aid','CORDAID Catholic Organisation for Relief and Development Aid', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('FHI 360','FHI 360', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('African Society for Laboratory Medicine','African Society for Laboratory Medicine', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Alter Vida','Alter Vida', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('OSISA Open Society Initiative for Southern Africa','OSISA Open Society Initiative for Southern Africa', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Malaria No More','Malaria No More', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Digital Good','Digital Good', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Windward Fund','Windward Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Sheikh Eid Bin Mohammed Al Thani Charity Foundation','Sheikh Eid Bin Mohammed Al Thani Charity Foundation', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Romanian Angel Appeal','Romanian Angel Appeal', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('WALIC West Africa Livestock Innovation Centre','WALIC West Africa Livestock Innovation Centre', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Association for a UN Live Museum','Association for a UN Live Museum', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('CAMEG Centrale d''achat des médicaments essentiels génériques et des consommables','CAMEG Centrale d''achat des médicaments essentiels génériques et des consommables', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('KARCPP King Abdullah Relief Campaign for the Pakistani People','KARCPP King Abdullah Relief Campaign for the Pakistani People', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('GCA Global Centre on Adaptation','GCA Global Centre on Adaptation', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('INT-NGO International Non-Governmental Organization','INT-NGO International Non-Governmental Organization', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNA USA United Nations Association of the USA','UNA USA United Nations Association of the USA', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('JSI Research and Training Institute, Inc.','JSI Research and Training Institute, Inc.', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Comic Relief','Comic Relief', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('MFM Menschen für Menschen','MFM Menschen für Menschen', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('PATH','PATH', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Silatech','Silatech', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Tearfund','Tearfund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('ClimateWorks Foundation','ClimateWorks Foundation', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('THPS Tanzania Health Promotion Support','THPS Tanzania Health Promotion Support', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('TMEA TradeMark East Africa','TMEA TradeMark East Africa', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('TDH Terre des Hommes Italy','TDH Terre des Hommes Italy', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('CRS Catholic Relief Services','CRS Catholic Relief Services', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('CBHF Clinton Bush Haiti Fund','CBHF Clinton Bush Haiti Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('One Earth','One Earth', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('IsraAID Israel Forum for International Humanitarian Aid','IsraAID Israel Forum for International Humanitarian Aid', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Association IPE','Association IPE', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('LDSC Later Day Saints Charities','LDSC Later Day Saints Charities', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('World Vision','World Vision', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('MFSL Médecins Sans Frontières Logistics','MFSL Médecins Sans Frontières Logistics', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('AmeriCares Foundation','AmeriCares Foundation', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Center for Health Policies and Studies PAS Center','Center for Health Policies and Studies PAS Center', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('IRW Islamic Relief Worldwide','IRW Islamic Relief Worldwide', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('KNCV Koninklijke Nederlandse Centrale Vereniging tot bestrijding der Tuberculose','KNCV Koninklijke Nederlandse Centrale Vereniging tot bestrijding der Tuberculose', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('PSI Population Services International','PSI Population Services International', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('OBR-NGO (National)','OBR-NGO (National)', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('AFC Asian Football Confederation','AFC Asian Football Confederation', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UMCOR United Methodist Committee on Relief','UMCOR United Methodist Committee on Relief', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('GCDP Global Commission on Drug Policy','GCDP Global Commission on Drug Policy', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Devnet International','Devnet International', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Millennium Promise','Millennium Promise', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('American Red Cross','American Red Cross', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('PBSP Philippine Business for Social Progress','PBSP Philippine Business for Social Progress', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('National Geographic Society','National Geographic Society', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Interpeace','Interpeace', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('IFA International Fertilizer Industry Association','IFA International Fertilizer Industry Association', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Caritas Internationalis','Caritas Internationalis', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Sustainable Markets Foundation','Sustainable Markets Foundation', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('SES Socios en Salud Sucursal Peru','SES Socios en Salud Sucursal Peru', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('FPN Fundacion Patagonia Natural','FPN Fundacion Patagonia Natural', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Soins de santé primaires en milieu rural (SANRU)','Soins de santé primaires en milieu rural (SANRU)', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Hammer Forum','Hammer Forum', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('NAT-NGO Non-Governmental Organization','NAT-NGO Non-Governmental Organization', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('CHAG Christian Health Association of Ghana','CHAG Christian Health Association of Ghana', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Save the Children','Save the Children', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('IFRC International Federation of Red Cross and Red Crescent Societies','IFRC International Federation of Red Cross and Red Crescent Societies', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('QRCS Qatar Red Crescent Society','QRCS Qatar Red Crescent Society', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('IRC International Rescue Committee','IRC International Rescue Committee', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('OXFAM International','OXFAM International', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Woord en Daad','Woord en Daad', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Amref Health Africa in Kenya','Amref Health Africa in Kenya', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('OBR-NGO (International)','OBR-NGO (International)', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('SSACONG Congregation of the Sisters of Saint Anne','SSACONG Congregation of the Sisters of Saint Anne', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('RBM Roll Back Malaria','RBM Roll Back Malaria', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('IUCN International Union for Conservation of Nature','IUCN International Union for Conservation of Nature', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('IATI-TF International Aid Transparency Initiative Trust Fund','IATI-TF International Aid Transparency Initiative Trust Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('The Defeat-NCD Partnership','The Defeat-NCD Partnership', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Stop TB Partnership','Stop TB Partnership', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('SUN Scaling Up Nutrition Movement','SUN Scaling Up Nutrition Movement', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Global Alliance for Clean Cookstoves','Global Alliance for Clean Cookstoves', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('GHL Global Humanitarian Lab','GHL Global Humanitarian Lab', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('IATI International Aid Transparency Initiative','IATI International Aid Transparency Initiative', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('CoNISMa Consorzio Nazionale Interuniversitario per le Scienze del Mare','CoNISMa Consorzio Nazionale Interuniversitario per le Scienze del Mare', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('DIIS Danish Institute for International Studies','DIIS Danish Institute for International Studies', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('ITRC International Tuberculosis Research Center','ITRC International Tuberculosis Research Center', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('University of Oxford','University of Oxford', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('IFPRI International Food Policy Research Institute','IFPRI International Food Policy Research Institute', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('SwedBio Swedish International Biodiversity Programme','SwedBio Swedish International Biodiversity Programme', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Columbia University','Columbia University', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('University of Genova','University of Genova', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('University of Notre Dame','University of Notre Dame', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UPNFM National Pedagogical University Francisco Morazan','UPNFM National Pedagogical University Francisco Morazan', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('LSTM Liverpool School of Tropical Medicine','LSTM Liverpool School of Tropical Medicine', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('ICARDA International Center for Agricultural Research in the Dry Areas','ICARDA International Center for Agricultural Research in the Dry Areas', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('GELI Global Executive Leadership','GELI Global Executive Leadership', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('CLAEH Latin American Centre for Human Economy','CLAEH Latin American Centre for Human Economy', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('ACFE Association of Certified Fraud Examiners','ACFE Association of Certified Fraud Examiners', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('OFID OPEC Fund for International Development','OFID OPEC Fund for International Development', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('CAF Development Bank of Latin America','CAF Development Bank of Latin America', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('IADB Inter-American Development Bank','IADB Inter-American Development Bank', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('BCIE Central American Bank for Economic Integration','BCIE Central American Bank for Economic Integration', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('IsDB Islamic Development Bank','IsDB Islamic Development Bank', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('CDB Caribbean Development Bank','CDB Caribbean Development Bank', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('AfDB African Development Bank','AfDB African Development Bank', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('ADB Asian Development Bank','ADB Asian Development Bank', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('EBRD European Bank for Reconstruction and Development','EBRD European Bank for Reconstruction and Development', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('AIIB Asian Infrastructure Investment Bank','AIIB Asian Infrastructure Investment Bank', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('IMF International Monetary Fund','IMF International Monetary Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('AFESD Arab Fund for Economic and Social Development','AFESD Arab Fund for Economic and Social Development', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('CFC Common Fund for Commodities','CFC Common Fund for Commodities', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Cities Alliance','Cities Alliance', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('GCF Green Climate Fund','GCF Green Climate Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('GGGI Global Green Growth Institute','GGGI Global Green Growth Institute', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('GPE Global Partnership for Education','GPE Global Partnership for Education', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('SEforALL Sustainable Energy for All','SEforALL Sustainable Energy for All', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Nutrition International','Nutrition International', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Nansen Initiative','Nansen Initiative', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('ARISE Private Sector Alliance for Disaster Resilient Societies (formerly R!SE)','ARISE Private Sector Alliance for Disaster Resilient Societies (formerly R!SE)', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Somalia Stability Fund','Somalia Stability Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UNITAID International Drug Purchase Facility','UNITAID International Drug Purchase Facility', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('WSSCC Water Supply and Sanitation Collaborative Council','WSSCC Water Supply and Sanitation Collaborative Council', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('GAVI Global Alliance for Vaccination and Immunization','GAVI Global Alliance for Vaccination and Immunization', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('GEF Global Environment Facility','GEF Global Environment Facility', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('3DF Three Disease Fund','3DF Three Disease Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('LIFT Livelihoods and Food Security Fund','LIFT Livelihoods and Food Security Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('PONREPP-TF Post-Nargis Response and Preparedness Plan Trust Fund','PONREPP-TF Post-Nargis Response and Preparedness Plan Trust Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('DAG Development Assistance Group','DAG Development Assistance Group', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('AF Adaptation Fund','AF Adaptation Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Montreal Protocol','Montreal Protocol', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('JPF Joint Peace Fund','JPF Joint Peace Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('ICMPD International Centre for Migration Policy Development','ICMPD International Centre for Migration Policy Development', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('JPP Somalia Joint Police Programme','JPP Somalia Joint Police Programme', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('ICAT Initiative for Climate Action Transparency','ICAT Initiative for Climate Action Transparency', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Energy Transition Partnership','Energy Transition Partnership', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Peace Process Support - The Secretariat','Peace Process Support - The Secretariat', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('The Climate Vulnerable Forum & Vulnerable Twenty Group of Ministers of Finance','The Climate Vulnerable Forum & Vulnerable Twenty Group of Ministers of Finance', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Joint Support to Somaliland National Electoral Commission','Joint Support to Somaliland National Electoral Commission', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('SHF Sanitation and Hygiene Fund','SHF Sanitation and Hygiene Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('CMI Center for Mediterranean Integration','CMI Center for Mediterranean Integration', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('ATscale, the Global Partnership for Assistive Technology','ATscale, the Global Partnership for Assistive Technology', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('NDC Partnership Fund','NDC Partnership Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('GFATM Global Fund to Fight Aids, Tuberculosis and Malaria','GFATM Global Fund to Fight Aids, Tuberculosis and Malaria', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('ARC African Risk Capacity','ARC African Risk Capacity', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('CAC Central American Agricultural Council','CAC Central American Agricultural Council', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('CILSS Permanent Inter-State Committee on Drought Control in the Sahel','CILSS Permanent Inter-State Committee on Drought Control in the Sahel', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UN ECCAS Economic Community of Central African States','UN ECCAS Economic Community of Central African States', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('ECOWAS Economic Community of West African States','ECOWAS Economic Community of West African States', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('G77 Group of 77','G77 Group of 77', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('GFDRR Global Facility for Disaster Reduction and Recovery','GFDRR Global Facility for Disaster Reduction and Recovery', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('GLOBE International Global Legislators Organisation','GLOBE International Global Legislators Organisation', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('IGAD Intergovernmental Authority on Development','IGAD Intergovernmental Authority on Development', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('MERCOSUR Southern Common Market','MERCOSUR Southern Common Market', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('OECD Organisation for Economic Co-operation and Development','OECD Organisation for Economic Co-operation and Development', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('OIRSA Organismo Internacional Regional De Sanidad Agropecuaria','OIRSA Organismo Internacional Regional De Sanidad Agropecuaria', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('UEMOA West African Economic and Monetary Union','UEMOA West African Economic and Monetary Union', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('IRENA International Renewable Energy Agency','IRENA International Renewable Energy Agency', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('CTBTO Preparatory Commission for the Nuclear-Test-Ban Treaty Organization','CTBTO Preparatory Commission for the Nuclear-Test-Ban Treaty Organization', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('NBI Nile Basin Initiative','NBI Nile Basin Initiative', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('SADC Southern African Development Community','SADC Southern African Development Community', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('OSCE Organization for Security and Co-operation in Europe','OSCE Organization for Security and Co-operation in Europe', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('OECS Organisation of Eastern Caribbean States','OECS Organisation of Eastern Caribbean States', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('OPEC Organization of the Petroleum Exporting Countries','OPEC Organization of the Petroleum Exporting Countries', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Nordic Development Fund','Nordic Development Fund', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('PIFS Pacific Islands Forum Secretariat','PIFS Pacific Islands Forum Secretariat', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('OIF Organisation internationale de la Francophonie','OIF Organisation internationale de la Francophonie', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Office of the Quartet','Office of the Quartet', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('ICC International Criminal Court','ICC International Criminal Court', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Itaipu Binacional','Itaipu Binacional', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('G5 Sahel Group of Five for the Sahel','G5 Sahel Group of Five for the Sahel', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('RSHQ Resolute Support HQ – NATO','RSHQ Resolute Support HQ – NATO', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('C40 Climate Leadership Group','C40 Climate Leadership Group', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('ISA International Solar Alliance','ISA International Solar Alliance', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('ECSAHC East, Central, and Southern Africa Health Community','ECSAHC East, Central, and Southern Africa Health Community', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('SACEP South Asia Cooperative Environment Programme','SACEP South Asia Cooperative Environment Programme', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('EBY Entidad Binacional Yacyretá','EBY Entidad Binacional Yacyretá', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('ASEAN Association of Southeast Asian Nations','ASEAN Association of Southeast Asian Nations', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('AGFUND Arab Gulf Fund for Development','AGFUND Arab Gulf Fund for Development', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Slovenia','Slovenia', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('test level 4','test level 4', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('test level 3','test level 3', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Sample Cat 3','Sample Cat 3', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('ADMIN - PARTNER CATEGORY - E2E','QA SAMPLE FOR TETSING', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('ADM USER - PARTNER CATEGORY - AUTOMATED','ADM USER - LIAISON OFFICE - AUTOMATED', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('FD partner category','FD partner category', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('FD partner category child','FD partner category child', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Test opp test PC','Test opp test PC', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('new PC for QA','test', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('another new pc','another new pc', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('DC QA Partner Category','PRM E2E Testing', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Automated Partner Category azU6','Category created with Katalon Automation', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Automated Partner Category 01','Category created with Katalon Automation', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Automated Partner Category hBgw','Category created with Katalon Automation', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Automated Partner Category J87M','Category created with Katalon Automation', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Automated Partner Category KA7T','Category created with Katalon Automation', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Automated Partner Category EGrZ','Category created with Katalon Automation', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('QAPS NEW PARTNR CATEGORY','QA SAMPLE FOR TESTING', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0),
  ('Automated Partner Category W0Dm','Category created with Katalon Automation', 'UNOPSPartnerCategory', 1, 0, NOW(), 0, false, 0);