INSERT INTO
  "public"."OrganizationUnits" ("Code", "Name", "Discriminator", "Status", "CreatedBy", "CreatedDate", "LastModifiedBy", "IsDeleted", "DeletedBy")
VALUES
  ('B0002','CRP, EO, Executive Office', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B0002-ESU','CPG, Executive Support Team', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B0002-ET','CRP, EO, Ethics Team', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B0002-OPSEO','Former - B0002-OPSEO', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B0002-OPSET','EO, Ethics Team', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B0002-ST','Security Team', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B0004','MP, FG, Finance Group', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B0005','MP, SSC, IPAS', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B0006','CRP, CLT, Corporate Learning and Training', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B0008','OGC, HQCPC, HQ Contracts and Property Committee', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B0009','MP, ITG, IT Group', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B0010','IPMG, frm. Infrastructure', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B0012','MP, PG, Procurement Group', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B0026','Corporate, Copenhagen Office (Team) (Not in OD 15)', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B0034','Non - Specific Staff (Team) (Not in OD 15)', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B0036','CRP, COCO, Corporate Commitments', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B0037','CRP, STG, Strategy and Transformation Group', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B0038','CRP, ST, Strategic Transformation', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B0040','CRP, LG, Legal Group', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B0041','RQG, Risk and Quality Group', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B0042','MP, PCG, People and Culture Group', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B0043','CRP, NYBER, New York Board and External Relations Office', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B0044','Corporate Performance and Management Group (Team) (Not in OD 15)', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B0046','IN, IAIG, Intl Aud and Inv Group', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B0047','DP, PLG, Partnerships and Liaison Group', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B0047-EST','CPG, Executive Support Team', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B0048','CRP, CG, Communications Group', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B0049','MP, SSC, BSSC, Bangkok Shr Serv Centre', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B0050','ECR, ECROD, Office of the RD', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B0051','AR, AROD, Office of the RD', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B0051-OPSEMOATOC','Former - B0051-OPSEMOATOC', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B0051-OPSEMOCPHIW','Former - B0051-OPSEMOCPHIW', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B0051-OPSEUOMKOC','Former - B0051-OPSEUOMKOC', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B0052','CPG, frm. Mgt Advisory Serv.', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B0053','AFR, AFROD, Office of the RD', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B0054','LCR, LCROD, Office of the RD', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B0055','Partnerships PPG (Not in OD 15)', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B0055-OPSAPOTLOC','Former - B0055-OPSAPOTLOC', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B0056','Former - Middle East Office', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B0058','MP, SSC, Shared Services Centre', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B0059','MP, IPMG, Infra and PM Group', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B0060','RP, RP, Regional Portfolios', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B0061','DP, ODP, Office of the DED - Delivery & Partnerships', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B0062','MP, OMP, Office of the DED - Management & Policy', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B0063','MP, RCG, Risk and Compliance Group', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B0064','MP, PID, Process Innovation and Digitalisation', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B0201','IN, ETO, Ethics Office', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B0401','FPG, Revenue Centre (Team (Revenue)) (Not in OD 15)', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B0402','FA, CFOO, Office of the CFO', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B0403','FA, CS, Corporate Strategy', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B1201','PG, Operations', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B1202','SPPG, UNGM (Team (Revenue)) (Not in OD 15)', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B3601','Corporate, Staff Reimbursement (Team) (Not in OD 15)', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B3602','Corporate, Chrysler Building (Team) (Not in OD 15)', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B3603','CRP, CIF, Corporate Investment Fund', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B3604','Corporate, Grants (Team) (Not in OD 15)', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B3605','Corporate, Investments AEMO (Team) (Not in OD 15)', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B3606','Corporate, Investments AFO (Team) (Not in OD 15)', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B3607','Corporate, Investments GPSO (Team) (Not in OD 15)', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B3608','Corporate, Investments LCO (Team) (Not in OD 15)', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B3609','Corporate, Investments SIPG (Team) (Not in OD 15)', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B3610','Corporate, Investments SPMPG (Team) (Not in OD 15)', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B3611','Corporate, Investments SPPG', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B3612','Corporate, Investments CPG (Team) (Not in OD 15)', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B3613','Corporate, Investments PCPG (Team) (Not in OD 15)', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B3614','Corporate, Investments FPG (Team) (Not in OD 15)', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B3615','Corporate, Investments CSPG (Team) (Not in OD 15)', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B3616','Corporate, Investments PPG (Team) (Not in OD 15)', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B3617','BIIP, Buz Innov & Improv Prgm', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B3618','Corporate, Sustainability Program (Team) (Not in OD 15)', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B3619','CRP, CEB, Corporate Executive Board', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B3620','DP, HEL, Helsinki Office', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B3621','CRP, QMU, Quality Monitoring Unit', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B3622','CRP, MSC, Management Support Centre', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B4001','OGC, GCO, Office of the General Counsel', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B4201','PCPG, Revenue Centre (Team (Revenue)) (Not in OD 15)', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B4401','CPMG, Revenue Centre (Team) (Not in OD 15)', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B4701-BRU','LO, BRU, Brussels Liaison Team', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B4701-CPH','LO, Embedded Liaison Teams', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B4701-GVA','CPG, Geneva Liaison Team', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B4701-NBO','CPG, Nairobi Liaison Team', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B4701-TOK','CPG, Tokyo Liaison Team', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B4701-WAS','LO, WAS, Washington Liaison Team', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5001','GPO, NYPO, PSC, Peace and Security Cluster', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5002','GPO, GVA, Water, Environment & Climate (WEC)', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5003','GPO, NYPO, SDC, Grant Management Services', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5004','GPO, NYPO, Development and Special Initiatives Portfolio', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5005','GPSO, GVAC, Public Health (Cluster) (Not in OD 15)', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5006','AR, EAPMCO, Thailand', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5007','GPO, GVA, Geneva', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5008','CPG, Partnerships Team', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5009','GPO, GPOOD, Office of the Director', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5010','ECR, AUMCO, Austria', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5011','GPO, NYPO, UN Technology Support Services', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5012','GPO, NYPO, SDC, Sustainable Development Cluster', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5014','GPO, NYPO, PSC, Afghanistan Project Unit', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5015','GPO, NYPO, PSC, Iraq Project Unit', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5016','GPO, NYPO, PSC, Syria Project Unit', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5017','GPO, NYPO, PSC, Somalia Project Unit', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5018','GPO, NYPO, PSC, South Sudan Project Unit', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5019','GPO, NYPO, PSC, Sudan Project Unit', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5020','GPO, NYPO, PSC, Abyei Project Unit', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5021','NYPO, PSC, Darfur Project Unit', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5022','GPO, NYPO, PSC, Lebanon Project Unit', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5023','GPO, NYPO, PSC, Palestine Project Unit', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5024','GPO, NYPO, PSC, Western Sahara Project Unit', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5025','GPO, NYPO, PSC, DRC Project Unit', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5026','GPO, NYPO, PSC, Mali Project Unit', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5027','GPO, NYPO, PSC, CAR Project Unit', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5028','GPO, NYPO, PSC, Libya Project Unit', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5029','GPO, NYPO, PSC, Colombia Project Unit', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5030','NYPO, PSC, Cyprus Project Unit', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5031','GPO, NYPO, PSC, Burkina Faso Project Unit', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5032','GPO, NYPO, PSC, Nigeria Project Unit', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5033','GPO, NYPO, PSC, Ethiopia Project Unit', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5034','GPO, NYPO, PSC, Ukraine Project Unit', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5101','AR, AFCO, Afghanistan', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5102','Former - EMO, Arab States Cluster', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5103','Former - EMO, International WtrsCluster', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5104','MR, AMMMCO, Amman', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5105','Former - EMO, Italy', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5106','MR, JRSCO, Jerusalem', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5107','ECR, AUMCO,  Pristina', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5108','Former - EMO, Switzerland', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5109','ECR, RSMCO, Serbia', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5110','ECR, RSMCO, Serbia MCO', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5112','AFR, TNPC, Tunisia - 2013', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5114','ECR, GVA, Stop TB', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5115','ECR, GVA, Cities Alliance', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5116','ECR, UAMCO, Ukraine MCO', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5117','ECR, GVA, WASH', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5118','ECR, GVA, EIF', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5119','ECR, GVA, UN Partners', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5120','MR, MROD, Office of the RD', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5121','MR, AMMMCO, Iraq', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5122','MR, AMMMCO, Lebanon', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5123','MR, AMMMCO, Syria', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5124','MR, AMMMCO, Yemen', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5130','ECR, AUMCO,  Georgia', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5131','ECR, AUMCO,  Albania', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5132','ECR, AUMCO, Austria MCO', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5133','ECR, AUMCO, Uzbekistan', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5141','ECR, GVA, LID', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5142','ECR, GVA, RGP', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5143','ECR, GVA, SUN', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5144','ECR, GVA, S4AT', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5145','ECR, GVA, Advisory Services', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5146','ECR, GVA, RBM Partnership (RBM)', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5147','ECR, GVA, GELI - CMI - PDD', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5148','ECR, GVA, ATscale Partnership (ATscale)', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5149','ECR, GVA, Sanitation and Hygiene Fund (SHF)', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5150','ECR, GVA, UN Partners HR Services', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5151','ECR, GVA, UN Partners Project Services', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5152','ECR, GVA, S4All UNW ATP', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5160','MR, COE, Infra and PM Center of Excellence', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5201','MAS, Revenue Centre (Team (Revenue)) (Not in OD 15)', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5301','AFR, CDMCO, DR Congo', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5302','AFR, SNMCO, Senegal MCO', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5303','AFR, KEMCO, Kenya MCO', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5304','AFR, ETMCO, South Sudan', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5305','AFR, SNMCO, Senegal', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5306','AFR, SNMCO, TNPO, Tunisia', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5307','Former - AFR, frm. Johannesburg Cluster', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5308','AFR, ETMCO, Ethiopia', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5309','AFR, GHMCO, Liberia', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5310','AFR, SNMCO, Mali', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5311','AFR, SOCO, Somalia', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5312','AFR, ETMCO, Sudan', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5313','AFR, CDMCO, Central African Rep', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5314','AFR, GHMCO, Ghana', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5315','AFR, GHMCO, Gambia', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5316','AFR, GHMCO, Nigeria', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5317','AFR, GHMCO, Sierra Leone', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5318','AFR, ETMCO, Djibouti', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5319','AFR, SNMCO, Côte d’Ivoire', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5320','AFR, SNMCO, Guinea', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5321','AFR, SNMCO, Niger', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5322','AFR, SNMCO, Burkina Faso', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5323','AFR, KEMCO, Kenya', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5324','AFR, SNMCO, TNPO, Morocco', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5325','AFR, SNMCO, TNPO, Libya', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5326','AFR, SNMC, temporary', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5327','AFR, KEMCO, Mozambique', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5328','AFR, CDMCO, DR Congo MCO', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5329','AFR, KEMCO, Zimbabwe', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5330','AFR, SNMCO, Guinea-Bissau', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5331','AFR, KEMCO, Uganda', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5332','AFR, GHMCO, Ghana MCO', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5333','AFR, ETMCO, Ethiopia MCO', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5334','AFR, KEMCO, Zambia', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5335','AFR, KEMCO, Tanzania', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5336','AFR, KEMCO, Malawi', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5401','LCR, ARMCO, Argentina', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5404','LCR, PEMCO, Colombia', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5405','LCR, GTCO, Guatemala', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5406','LCR, HTCO, Haiti', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5407','LCR, NICO, Nicaragua', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5408','LCR, PAMCO, Panama', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5410','LCR, PEMCO, Peru', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5411','LCR, ARMCO, Paraguay', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5412','LCR, HNMCO, El Salvador', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5413','LCR, ARMCO, Uruguay', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5414','LCR, ARMCO, Brazil', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5416','LCR, PAMCO, Costa Rica', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5417','LCR, HNMCO, Honduras', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5418','LCR, PAMCO, Saint Lucia', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5419','LCR, PAOH, Panama Hub', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5420','LCR, AROH, Argentina Hub', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5421','LCR, MXCO, Mexico', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5422','LCR, ARMCO, Argentina  MCO', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5423','LCR, PAMCO, Panama MCO', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5424','LCR, PEMCO, Peru MCO', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5425','LCR, HNMCO, Honduras MCO', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5501','Former - AEMO, Thailand', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5502','AR, EAPMCO, Indonesia', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5503','AR, SAMCO, India', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5505','AR, SAMCO, Sri Lanka', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5506','AR, MMCO, Myanmar', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5507','AR, SAMCO, Pakistan', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5508','AEMO, LKOH, Maldives (Monitoring Unit) (Not in OD 15)', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5509','AR, KHMCO, Cambodia MCO', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5510','AR, EAPMCO, Mekong Project Office', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5511','AR, EAPMCO, China', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5512','AR, EAPMCO, Philippines', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5514','AR, SAMCO, Bangladesh', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5515','AR, LKOH, Bhutan', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5516','AR, SAMCO, Nepal', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5517','AR, SAMCO, Sri Lanka MCO', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5518','AR, ARHC, Regional Health Cluster', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5519','AR, EAPMCO, Vietnam', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5520','AR, EAPMCO, Lao PDR', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5521','AR, EAPMCO, Pacific Operations Cluster', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5523','AR, EAPMCO, Thailand MCO', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5524','AR, EAPMCO, Papua New Guinea', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5801','CSPG ICT, Revenue Centre (Team (Revenue)) (Not in OD 15)', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5901','IPS, IPSO, IPS Office', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('B5902','IPS, PS, Portfolio Support', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('MAS','Former - MAS', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0),
  ('UNDP','Former - UNDP', 'UNOPSOrganizationUnit', 1, 0, NOW(), 0, false, 0);