INSERT INTO public."PartnerTrees"
("Name", "Code", "Description", "Type", "Parent", "Status", "Discriminator", "CreatedBy", "CreatedDate", "LastModifiedBy", "LastModifiedDate", "IsDeleted", "DeletedBy")
VALUES
('PPP Public Private Partnership','PPP','PPP','Level_1','', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Other','OTHER','Other','Level_1','', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Government','GOVERNMENT','Government','Level_1','', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Academic, Training and Research','ACADEMIC_TRAINING_RESEARC','Academic, Training and Research','Level_1','', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Multilateral','MULTILATERAL','Multilateral','Level_1','', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Non-governmental Organizations','NGO','NGO','Level_1','', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Private Sector','PRIVATE_SECTOR','Private Sector','Level_1','', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Foundation','FOUNDATION','Foundation','Level_1','', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('UNDP United Nations Development Programme','UNDP','UNDP','Level_4','FUND_PROGRAMME', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('WHO / PAHO World Health Organization incl. PAHO','WHO_PAHO','WHO','Level_4','SPECIALIZED_AGENCIES', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('UN EOSG Executive Office of the Secretary-General','EOSG','UN EOSG','Level_4','DEPARTMENT_OFFICE', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('EC European Commission','EC','EC','Level_4','EU', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('UN DOS Department of Operational Support','DOS','UN DOS','Level_4','DEPARTMENT_OFFICE', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('UN DPPA Department of Political and Peacebuilding Affairs','DPPA','UN DPPA','Level_4','DEPARTMENT_OFFICE', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('UN DPO Department of Peace Operations','DPO','UN DPO','Level_4','DEPARTMENT_OFFICE', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('UNOPS United Nations Office for Project Services','UNOPS','UNOPS','Level_4','OTHER_ENTITIES', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('OECD/DAC Government','OECD_DAC','Gov: OECD/DAC','Level_2','GOVERNMENT', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Vertical Fund','VERTICAL_FUND','Vertical Fund','Level_2','MULTILATERAL', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Non-OECD/DAC Government','NON_OECD_DAC','Gov: Non-OECD/DAC','Level_2','GOVERNMENT', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Regional and other Intergovernmental Organizations','REG_OTH_INGO','Regional & Other IGO','Level_2','MULTILATERAL', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('United Nations inter-agency pooled funds incl. Joint Programmes','UN_INTER_POOLED_FUND','UN inter-agency pooled funds incl. JPs','Level_2','MULTILATERAL', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('IFI International Financial Institutions','IFI','IFI','Level_2','MULTILATERAL', '1','s',1,NOW(),1,NOW(),FALSE,0),
('Multi-partner initiatives','MPI','MPI','Level_2','MULTILATERAL', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('United Nations','UNITED_NATIONS','UN','Level_2','MULTILATERAL', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Belgium','BELGIUM','Belgium','Level_3','OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Australia','AUSTRALIA','Australia','Level_3','OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('United Nations Coordination Mechanisms','UN_COORD','UN Coordination Mechanisms','Level_3','UNITED_NATIONS', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('South Korea','KOREA','South Korea','Level_3','OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('United Nations Subsidiary Organs','SUBSIDIARY_ORG','UN Subsidiary Organs','Level_3','UNITED_NATIONS', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Libya','LIBYA','Libya','Level_3','NON_OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Germany','GERMANY','Germany','Level_3','OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Guatemala','GUATEMALA','Guatemala','Level_3','NON_OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('New Zealand','NEW_ZEALAND','New Zealand','Level_3','OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Netherlands','NETHERLANDS','Netherlands','Level_3','OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Brazil','BRAZIL','Brazil','Level_3','NON_OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Panama','PANAMA','Panama','Level_3','NON_OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Poland','POLAND','Poland','Level_3','OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('United Nations Other Bodies','OTHER_BODIES','UN Other Bodies','Level_3','UNITED_NATIONS', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Ireland','IRELAND','Ireland','Level_3','OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Qatar','QATAR','Qatar','Level_3','OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Iceland','ICELAND','Iceland','Level_3','OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Spain','SPAIN','Spain','Level_3','OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Ecuador','ECUADOR','Ecuador','Level_3','NON_OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('China','CHINA','China','Level_3','NON_OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Turkey','TURKEY','Turkey','Level_3','NON_OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Ukraine','UKRAINE','Ukraine','Level_3','NON_OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('South Africa','SOUTH_AFRICA','South Africa','Level_3','NON_OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('EIF Enhanced Integrated Framework','EIF','EIF','Level_3','MPI', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('United Nations Related Organizations','RELATED_ORG','UN Related Organizations','Level_3','UNITED_NATIONS', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('United Nations Regional Commissions','REG_COMMISSION','UN Regional Commissions','Level_3','UNITED_NATIONS', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('3MDG/Myanmar Access for Health','3MDG_MAH','3MDG / MAH','Level_3','MPI', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Finland','FINLAND','Finland','Level_3','OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Canada','CANADA','Canada','Level_3','OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Liechtenstein','LIECHTENSTEIN','Liechtenstein','Level_3','NON_OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('United Nations Specialized Agencies','SPECIALIZED_AGENCIES','UN Specialized Agencies','Level_3','UNITED_NATIONS', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('United Nations Other Entities','OTHER_ENTITIES','UN Other Entities','Level_3','UNITED_NATIONS', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Morocco','MOROCCO','Morocco','Level_3','NON_OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Norway','NORWAY','Norway','Level_3','OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Denmark','DENMARK','Denmark','Level_3','OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('UK United Kingdom','UK','UK','Level_3','OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('India','INDIA','India','Level_3','NON_OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Gambia','GAMBIA','Gambia','Level_3','NON_OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Costa Rica','COSTA_RICA','Costa Rica','Level_3','NON_OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('USA United States of America','USA','USA','Level_3','OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Honduras','HONDURAS','Honduras','Level_3','NON_OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('France','FRANCE','France','Level_3','OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('AU African Union','AU','AU','Level_3','REG_OTH_INGO', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('EU European Union','EU','EU','Level_3','REG_OTH_INGO', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Austria','AUSTRIA','Austria','Level_3','OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Peru','PERU','Peru','Level_3','NON_OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Switzerland','SWITZERLAND','Switzerland','Level_3','OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('United Nations Departments and Offices','DEPARTMENT_OFFICE','UN Departments and Offices','Level_3','UNITED_NATIONS', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Luxembourg','LUXEMBOURG','Luxembourg','Level_3','OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Sweden','SWEDEN','Sweden','Level_3','OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Ethiopia','ETHIOPIA','Ethiopia','Level_3','NON_OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Greece','GREECE','Greece','Level_3','OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('GFATM Global Fund to Fight Aids, Tuberculosis and Malaria','GFATM','GFATM','Level_3','VERTICAL_FUND', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Israel','ISRAEL','Israel','Level_3','NON_OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('United Nations Research and Training','RESEARCH_TRAINING','UN Research and Training','Level_3','UNITED_NATIONS', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Portugal','PORTUGAL','Portugal','Level_3','OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('United Nations Funds and Programmes','FUND_PROGRAMME','UN Funds and Programmes','Level_3','UNITED_NATIONS', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Paraguay','PARAGUAY','Paraguay','Level_3','NON_OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Mexico','MEXICO','Mexico','Level_3','NON_OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Regional and other Financial Insitutions','REG_OTH_FI','Reg & other Financial Insitutions','Level_3','IFI', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Eswatini','ESWATINI','Eswatini','Level_3','NON_OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Saudi Arabia','SAUDI_ARABIA','Saudi Arabia','Level_3','NON_OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Japan','JAPAN','Japan','Level_3','OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('WBG World Bank Group','WBG','WBG','Level_3','IFI', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('United Nations Conventions and Frameworks','CONVENTION_FRAMEWORK','UN Conventions and Frameworks','Level_3','UNITED_NATIONS', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Sierra Leone','SIERRALEONE','Sierra Leone','Level_3','NON_OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Bangladesh','BANGLADESH','Bangladesh','Level_3','NON_OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Barbados','BARBADOS','Barbados','Level_3','NON_OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Clinton Health Access Initiative','ClintonHealthAccess','CHAI','Level_2','NGO', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Comisión nacional de prevención de riesgos y atención de emergencias','CNECR','CNE','Level_3','NON_OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Institituto Costarricense de Ferrocarriles','INCOFER','INCOFER','Level_3','NON_OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Global Alliance for a Sustainable Planet','GlobalAllianceForASustPla','GASP','Level_2','FOUNDATION', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Fund for Reconstruction and Development of the Republic of Uzbekistan','FRDRepUZB','Fund for Reconstruction and Development of the Republic of Uzbekistan','Level_3','NON_OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('The Climate and Society Institute','ICS01','ICS','Level_2','FOUNDATION', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Plan International Liberia','PLINTLIB','Plan International Liberia','Level_2','NGO', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Minderoo Foundation','MindFund','Minderoo Foundation','Level_2','FOUNDATION', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Indonesia','INDONESIA','Indonesia','Level_3','NON_OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('International Medical Corps','IntMedCorps','International Medical Corps','Level_2','NGO', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Sergey Brin Family Foundation','SGFF001','Sergey Brin Family Foundation','Level_2','FOUNDATION', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('International Medical Corps US','IntMedCorpUS','International Medical Corps US','Level_2','NGO', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Global Institute For Disease Elimination','GLIDE001','Global Institute For Disease Elimination','Level_2','PRIVATE_SECTOR', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('EPMMOP','epmmop001','EMPRESA PÚBLICA METROPOLITANA DE MOVILIDAD Y OBRAS PÚBLICAS','Level_4','ECUADOR', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Kharkiv City Council','KharkivCityCouncil','Kharkiv CC','Level_4','UKRAINE', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('CPP - Companhia Paulista de Parcerias','CompanhiaPaulista','CPP','Level_4','BRAZIL', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('The Forest & Climate Leaders’ Partnership','FCLP01','Forest & Climate Leaders’ Partnership','Level_3','MPI', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Baylor College of Medicine Children’s Foundation Eswatini','BCMCFE001','Baylor Foundation Eswatini','Level_2','FOUNDATION', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Rockefeller Brothers Fund','RBF001','Rockefeller Brothers Fund','Level_2','FOUNDATION', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('NATO','NATO','NATO','Level_3','REG_OTH_INGO', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Population Services International Madagascar','PSIMad','PSI Madagascar','Level_2','NGO', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('USMBHC','USMBHC001','The United States-Mexico Border Health Commission','Level_3','REG_OTH_INGO', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Uzbekistan','UZB001','Uzbekistan','Level_3','NON_OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Swaniti Initiative','swaniti001','Swaniti Initiative','Level_2','NGO', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Plan International Mali','PlanIntMali001','Plan International Mali','Level_2','NGO', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Italy','ITA001','Italiy','Level_3','OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Kuwait','KW001','Kuwait','Level_3','OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('United Arab Emirates','UAE001','UAE','Level_3','OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Oman','OMAN001','Oman','Level_3','NON_OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('DRC','DRC001','Danish Refugee Council','Level_2','NGO', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Zambia','ZAMBIA001','Zambia','Level_3','NON_OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('RF Catalytic Capital','RFCC1','RF Catalytic Capital','Level_2','NGO', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Fuel Distribution Gaza','FDG001','Fuel Distribution Gaza','Level_3','MPI', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('tbd','BOAD','0','Level_3','IFI', '0','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('West African Development Bank','BOAD1','BOAD','Level_4','REG_OTH_FI', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Argentina','ARG01','Argentina','Level_3','NON_OECD_DAC', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('The Santiago Network','SANTNET1','Santiago Network','Level_3','MPI', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0),
('Global Climate Action Partnership','GCAP01','GCAP','Level_3','MPI', '1','UNOPSPartnerTree',1,NOW(),1,NOW(),FALSE,0)