// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using UNOPS.PAO.UNOPSDataAccess.Context;

#nullable disable

namespace UNOPS.PAO.UNOPSDataAccess.Migrations
{
    [DbContext(typeof(UNOPSAppDbContext))]
    [Migration("20250922093909_AddBaseEngagementPermissions")]
    partial class AddBaseEngagementPermissions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // This is a data-only migration - no schema changes
            // The model remains the same as the previous migration
        }
    }
}
