// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using UNOPS.PAO.UNOPSDataAccess.Context;

#nullable disable

namespace UNOPS.PAO.UNOPSDataAccess.Migrations
{
    [DbContext(typeof(UNOPSAppDbContext))]
    [Migration("20250112145500_AddMetadataColumnsToEvents")]
    partial class AddMetadataColumnsToEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // This migration adds JSONB columns to the events table
            // The model remains the same as the previous migration
        }
    }
}

