environments:
  production:
    branch_pattern: "^production$"
    environment: "Production"
    project_id: "unops-opportunityplus-prod"
    repo_name: "cloud-run-images"
    image_name_main: "cloud-run-images/opportunityplus-prod"
    image_name_ai: "cloud-run-images/opportunityplus-ai-prod"
    service_name_main: "opportunityplus-prod"
    service_name_ai: "opportunityplus-ai-prod"
    region: "europe-west4"
    sql_conn_string: "unops-opportunityplus-prod:europe-west4:unops-opportunityplus-prod-postgres-001"
    vpc_connector: "projects/unops-opportunityplus-prod/locations/europe-west4/connectors/opportunityplus-prod-vpc"
    secrets_main: "Prod_DB_Connection_String=Prod_DB_Connection_String:latest,GoogleDriveServiceAccount_JSON=GoogleDriveServiceAccount_JSON:latest,AI_Setup_Secret=AI_Setup_Secret:latest"
    db_secret_name: "Prod_DB_Connection_String"
    env_vars_ai: "CURRENT_ENV=prod,GOOGLE_CLOUD_PROJECT=unops-opportunityplus-prod,GOOGLE_CLOUD_LOCATION=europe-west4,GOOGLE_GENAI_USE_VERTEXAI=TRUE"
    credentials_id: "cicd-sa-oplus-prod"
    invoker_service_accounts_main: "service-70092411004@gcp-sa-iap.iam.gserviceaccount.com,cloudrun-integrations-sa@unops-opportunityplus-prod.iam.gserviceaccount.com"
    invoker_service_accounts_ai: "service-70092411004@gcp-sa-iap.iam.gserviceaccount.com,cloudrun-integrations-sa@unops-opportunityplus-prod.iam.gserviceaccount.com,pno-ai-service@unops-opportunityplus-prod.iam.gserviceaccount.com,371670193592-compute@developer.gserviceaccount.com"
    dockerfile_main: "Dockerfile.prod"
    port_main: "7123"
    main_min_instances: "1"
    main_max_instances: "5"
    main_memory: "4Gi"
    main_cpu: "2"
    port_ai: "8080"
    ai_min_instances: "1"
    ai_max_instances: "10"
    ai_memory: "2Gi"
    ai_cpu: "1"
    main_concurrency: "160"
    ai_concurrency: "80"

  test:
    branch_pattern: "^test$"
    environment: "Test"
    project_id: "unops-opportunityplus-test"
    repo_name: "cloud-run-images"
    image_name_main: "cloud-run-images/opportunityplus-test"
    image_name_ai: "cloud-run-images/opportunityplus-ai-test"
    service_name_main: "opportunityplus-test"
    service_name_ai: "opportunityplus-ai-test"
    region: "europe-west4"
    sql_conn_string: "unops-opportunityplus-test:europe-west4:unops-opportunityplus-test-postgres-001"
    vpc_connector: "projects/unops-opportunityplus-test/locations/europe-west4/connectors/opportunityplus-test-vpc"
    secrets_main: "Test_DB_Connection_String=Test_DB_Connection_String:latest,GoogleDriveServiceAccount_JSON=GoogleDriveServiceAccount_JSON:latest,AI_Setup_Secret=AI_Setup_Secret:latest"
    db_secret_name: "Test_DB_Connection_String"
    env_vars_ai: "CURRENT_ENV=test,GOOGLE_CLOUD_PROJECT=unops-opportunityplus-test,GOOGLE_CLOUD_LOCATION=europe-west4,GOOGLE_GENAI_USE_VERTEXAI=TRUE"
    credentials_id: "cicd-sa-oplus-test"
    invoker_service_accounts_main: "service-11994381361@gcp-sa-iap.iam.gserviceaccount.com,cloudrun-integrations-sa@unops-opportunityplus-test.iam.gserviceaccount.com"
    invoker_service_accounts_ai: "service-11994381361@gcp-sa-iap.iam.gserviceaccount.com,cloudrun-integrations-sa@unops-opportunityplus-test.iam.gserviceaccount.com,pno-ai-service@unops-opportunityplus-test.iam.gserviceaccount.com,941171945910-compute@developer.gserviceaccount.com"
    dockerfile_main: "Dockerfile.test"
    port_main: "7123"
    main_min_instances: "0"
    main_max_instances: "3"
    main_memory: "2Gi"
    main_cpu: "2"
    port_ai: "8080"
    ai_min_instances: "1"
    ai_max_instances: "10"
    ai_memory: "2Gi"
    ai_cpu: "1"
    main_concurrency: "160"
    ai_concurrency: "80"
    
  qa:
    branch_pattern: "^development$"
    environment: "QA"
    project_id: "unops-opportunityplus-qa"
    repo_name: "cloud-run-images"
    image_name_main: "cloud-run-images/opportunityplus-qa"
    image_name_ai: "cloud-run-images/opportunityplus-ai-qa"
    service_name_main: "opportunityplus-qa"
    service_name_ai: "opportunityplus-ai-qa"
    region: "europe-west4"
    sql_conn_string: "unops-opportunityplus-qa:europe-west4:unops-opportunityplus-qa-postgres-001"
    vpc_connector: "projects/unops-opportunityplus-qa/locations/europe-west4/connectors/opportunityplus-qa-vpc"
    secrets_main: "QA_DB_Connection_String=QA_DB_Connection_String:latest,GoogleDriveServiceAccount_JSON=GoogleDriveServiceAccount_JSON:latest,AI_Setup_Secret=AI_Setup_Secret:latest"
    env_vars_ai: "CURRENT_ENV=qa,GOOGLE_CLOUD_PROJECT=unops-opportunityplus-qa,GOOGLE_CLOUD_LOCATION=europe-west4,GOOGLE_GENAI_USE_VERTEXAI=TRUE"
    credentials_id: "cicd-sa-oplus-qa"
    invoker_service_accounts_main: "service-11994381361@gcp-sa-iap.iam.gserviceaccount.com,cloudrun-integrations-sa@unops-opportunityplus-qa.iam.gserviceaccount.com"
    invoker_service_accounts_ai: "service-11994381361@gcp-sa-iap.iam.gserviceaccount.com,cloudrun-integrations-sa@unops-opportunityplus-qa.iam.gserviceaccount.com,pno-ai-service@unops-opportunityplus-qa.iam.gserviceaccount.com,351976372264-compute@developer.gserviceaccount.com"
    dockerfile_main: "Dockerfile.qa"
    port_main: "7123"
    main_min_instances: "0"
    main_max_instances: "3"
    main_memory: "2Gi"
    main_cpu: "2"
    port_ai: "8080"
    ai_min_instances: "1"
    ai_max_instances: "10"
    ai_memory: "2Gi"
    ai_cpu: "1"
    main_concurrency: "160"
    ai_concurrency: "80"

  development:
    branch_pattern: "^dev-deploy$"
    environment: "Dev"
    project_id: "unops-opportunityplus-dev"
    repo_name: "cloud-run-images"
    image_name_main: "cloud-run-images/opportunityplus-dev"
    image_name_ai: "cloud-run-images/opportunityplus-ai-dev"
    service_name_main: "opportunityplus-dev"
    service_name_ai: "opportunityplus-ai-dev"
    region: "europe-west4"
    sql_conn_string: "unops-opportunityplus-dev:europe-west4:unops-opportunityplus-dev-postgres-001"
    vpc_connector: "projects/unops-opportunityplus-dev/locations/europe-west4/connectors/opportunityplus-dev-vpc"
    secrets_main: "Dev_DB_Connection_String=Dev_DB_Connection_String:latest,GoogleDriveServiceAccount_JSON=GoogleDriveServiceAccount_JSON:latest,AI_Setup_Secret=AI_Setup_Secret:latest"
    env_vars_ai: "CURRENT_ENV=dev,GOOGLE_CLOUD_PROJECT=unops-opportunityplus-dev,GOOGLE_CLOUD_LOCATION=europe-west4,GOOGLE_GENAI_USE_VERTEXAI=TRUE"
    credentials_id: "cicd-sa-oplus-dev"
    invoker_service_accounts_main: "service-11994381361@gcp-sa-iap.iam.gserviceaccount.com,cloudrun-integrations-sa@unops-opportunityplus-dev.iam.gserviceaccount.com"
    invoker_service_accounts_ai: "service-11994381361@gcp-sa-iap.iam.gserviceaccount.com,cloudrun-integrations-sa@unops-opportunityplus-dev.iam.gserviceaccount.com,pno-ai-service@unops-opportunityplus-dev.iam.gserviceaccount.com,1074199687519-compute@developer.gserviceaccount.com"
    dockerfile_main: "Dockerfile.dev"
    port_main: "7123"
    main_min_instances: "0"
    main_max_instances: "3"
    main_memory: "512Mi"
    main_cpu: "1"
    port_ai: "8080"
    ai_min_instances: "1"
    ai_max_instances: "10"
    ai_memory: "2Gi"
    ai_cpu: "1"
    main_concurrency: "80"
    ai_concurrency: "80"
